In [1]:
import os
import pandas as pd
import numpy as np
print(os.getcwd()); # Prints the current working directory
os.chdir("C:/Users/RishuNikky/Documents/INSOFE/PHD/Datasets_and_Description/InputFiles") # Change directory
print(os.getcwd());

C:\Users\RishuNikky\Documents\INSOFE\All_Python
C:\Users\RishuNikky\Documents\INSOFE\PHD\Datasets_and_Description\InputFiles


In [5]:
data_aggrgated = pd.read_csv('save_perfect_data_12994.csv')

In [6]:
print(data_aggrgated.shape)
data_aggrgated.head()

(12994, 20)


ID drivingstyle  vehicle_len  veh_weight  axles  temparature  \
0  DR_10002       Normal          552        2027      2     2.200000   
1  DR_10013        Vague         1709       18599      6     4.000000   
2  DR_10023       Normal          552        1289      2     6.062500   
3  DR_10024   Aggressive         1768       14588      5     4.273387   
4  DR_10025        Vague         1734       16708      5     1.000000   

   weath_type  weath_intensity   humidity  wind_direction  wind_speed  \
0           0                0  66.600000      173.200000    5.800000   
1           0                0  58.000000      163.000000    8.000000   
2           0                0  34.062500      205.875000    3.062500   
3           2                0  83.753227      123.465146    4.300558   
4           0                0  87.000000       11.000000    3.000000   

   lighting_cond  Lane_road      speed  precd_veh_id  precd_veh_Speed  \
0              0   1.600000  84.400000   604778.0000        77.000000   
1              1   1.333333  86.555556   598360.0000        85.777778   
2              1   1.875000  83.125000   723420.5625        81.625000   
3              2   1.333333  86.666667   651093.5000        81.500000   
4              1   1.375000  81.500000   657985.2500        82.500000   

   precd_veh_weight  precd_veh_len  precd_veh_timegap  road_cond_weath  
0       4200.400000     762.000000         234.800000              0.0  
1       9517.888889    1184.888889         173.111111              0.0  
2      10180.187500    1022.312500          74.592548              0.0  
3       6366.333333    1069.666667         194.166667              0.0  
4      10157.875000    1113.625000         156.125000              3.0

In [7]:
data_y  = data_aggrgated['drivingstyle']
cols=['ID','drivingstyle','precd_veh_id']
data_x  = data_aggrgated.drop(cols,1)

In [8]:
print(data_x.shape)
print(data_y.shape)

(12994, 17)
(12994,)


In [28]:
# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
x_train, x_test, y_train, y_test = train_test_split(data_x, data_y, test_size = 0.05, random_state = 0)

In [29]:
X, y = x_train, y_train

In [30]:
from sklearn.ensemble import RandomForestClassifier

In [31]:
rfclsifer = RandomForestClassifier(random_state = 0)
rfclsifer.fit(X, y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [32]:
# Predicting the Test set results
y_pred = rfclsifer.predict(x_test)

In [33]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[ 81  57  12]
 [ 26 254  44]
 [ 20  21 135]]


In [34]:
y_pred

array(['Vague', 'Vague', 'Normal', 'Vague', 'Aggressive', 'Vague',
       'Normal', 'Normal', 'Vague', 'Vague', 'Normal', 'Normal', 'Normal',
       'Normal', 'Vague', 'Normal', 'Normal', 'Aggressive', 'Aggressive',
       'Normal', 'Normal', 'Normal', 'Vague', 'Aggressive', 'Aggressive',
       'Normal', 'Vague', 'Vague', 'Normal', 'Normal', 'Normal', 'Vague',
       'Normal', 'Normal', 'Vague', 'Vague', 'Normal', 'Aggressive',
       'Normal', 'Aggressive', 'Normal', 'Normal', 'Vague', 'Normal',
       'Normal', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal',
       'Vague', 'Normal', 'Normal', 'Normal', 'Normal', 'Normal',
       'Normal', 'Vague', 'Normal', 'Aggressive', 'Vague', 'Normal',
       'Normal', 'Normal', 'Vague', 'Aggressive', 'Vague', 'Aggressive',
       'Normal', 'Vague', 'Normal', 'Normal', 'Vague', 'Normal', 'Vague',
       'Normal', 'Aggressive', 'Normal', 'Vague', 'Vague', 'Aggressive',
       'Normal', 'Aggressive', 'Normal', 'Vague', 'Vague', 'Aggressive',
  

In [22]:
#test_pred_dataset.to_csv("test_pred_dataset.csv")
test_pred_dataset = pd.read_csv("test_pred_dataset.csv")

In [23]:
test_data_x = test_pred_dataset.copy()

In [24]:
test_data_x = test_data_x.drop('ID',1)
test_data_x

vehicle_len  veh_weight  axles  temparature  weath_type  \
0             548        2467      2     1.000000           0   
1             594        1794      2     1.880000           0   
2             825        5885      2     2.500000           1   
3             567        1655      2     5.500000           0   
4            1993       19417      6     5.000000           0   
5             550        1751      2     2.095238           0   
6            1688       25624      6     4.200000           0   
7             792        2592      2     8.000000           0   
8             551        1718      2     1.000000           0   
9            1709       10812      5     4.200000           0   
10            519        1575      2    11.000000           0   
11            556        1465      2     6.000000           0   
12           1719       33547      6     5.461538           0   
13            621        1801      2     7.333333           0   
14           1669       26166      6     8.100000           0   
15            462        1578      2     4.000000           0   
16           1733       14799      6     5.000000           0   
17           2092       16487      4     3.000000           0   
18            556        1699      2     6.000000           0   
19           2021       19842      5     6.333333           2   
20            567        1857      2     1.000000           0   
21           1684       23387      6     3.000000           0   
22            557        1637      2     0.000000           2   
23            591        1634      2     1.000000           0   
24           2061       23521      6     3.000000           0   
25           1342       10855      3     2.000000           0   
26           1675       38112      6     5.000000           0   
27            559        2104      2     8.000000           0   
28            584        1709      2     9.000000           0   
29           1719       11571      5    10.777778           0   
...           ...         ...    ...          ...         ...   
4850         2087       21103      5     7.000000           0   
4851          535        3569      2     2.434783           0   
4852          508        1740      2     2.875000           0   
4853          512        1597      2     4.000000           0   
4854         1692       17249      4     5.333333           0   
4855         1703       17097      4     7.461538           0   
4856          614        1671      2    -5.333333           0   
4857         1711       17170      5     3.000000           0   
4858         1671        7499      5     6.000000           0   
4859         1735       23403      6     7.142857           0   
4860          570        1892      2     6.000000           1   
4861         2037       24368      6     2.000000           0   
4862          666        2733      2     1.166667           0   
4863          523         939      2     7.000000           0   
4864          577        2056      2     9.000000           0   
4865         1760       27064      6     5.000000           0   
4866          504        1775      2     1.000000           0   
4867          684        3086      2     7.800000           1   
4868         1703       18291      6     9.000000           0   
4869         1645       12689      5     1.333333           0   
4870         1966       20674      5     1.000000           0   
4871          545        1741      2     6.000000           0   
4872          508        1312      2    -2.500000           0   
4873          768        2886      2     5.250000           0   
4874         1704       16468      6     7.000000           0   
4875          495        1295      2     2.117647           0   
4876         1710       17164      4     6.529412           0   
4877          542        2115      2     5.000000           0   
4878         1714       15282      6     2.783784           0   
4879         1669       11148      5     

In [26]:
# Predicting the Test set results with Random Forest
test_y_pred = rfclsifer.predict(test_data_x)

In [35]:
test_pred_dataset['drivingstyle'] = test_y_pred

In [36]:
final_prediction = pd.DataFrame()
final_prediction[['ID','DrivingStyle']] = test_pred_dataset.iloc[:][['ID','drivingstyle']]

In [37]:
final_prediction.to_csv("final_RF_Prediction_wtype.csv",index=False)